add logger
antisedativ/CharmLog pull request #19
Opened 2024-02-15 16:17 UTC by elfarr

2024-02-15 21:18 UTC, antisedativ requested changes

2024-02-15 21:18 UTC, antisedativ commented on src/utils/Logger.js
> +const logColor = ['#FFFFFF', '#0000FF', '#FF8000', '#F14065', '#FF0000'];
цвета можно брать из объекта цветов в константах, тем самым упростить метод
если какого то цвета не хватит, можешь добавить 

либо вообще создать еще один объект с уровнями в константах

2024-02-15 21:18 UTC, antisedativ commented on src/utils/Logger.js
> +    if (this.single_mode == true) {
true можно убрать, if можно объединить

2024-02-15 21:18 UTC, antisedativ commented on src/utils/Logger.js
> +    else {
else вряд ли нужен

2024-02-15 21:18 UTC, antisedativ commented on src/utils/Logger.js
> +    this.single_mode = single_mode || false;
тут наверное  лучше использовать ?? вместо ||

2024-02-15 21:22 UTC, antisedativ commented
Еще метод лучше убрать из utils и создать отдельную папку

2024-02-15 21:23 UTC, antisedativ commented
Еще нужно запулить себе мастер, без этого не получится внести правки - нет нужных файлов в твоей ветке

2024-02-15 21:32 UTC, elfarr commented
ок шеф

2024-02-17 21:58 UTC, antisedativ commented
посмотри такое решение (оно может не работать)

import { logLevelColors } from '../utils/constants.js';
export class Logger {
	#levels = {
		debug: 0,
		info: 1,
		warning: 2,
		error: 3,
		critical: 4,
	};

	constructor(logLevel = 'debug', single_mode = false) {
		this.logLevel = logLevel;
		this.single_mode = single_mode;
	}

	setLogLevel(logLevel, single_mode = false) {
		this.logLevel = logLevel;
		this.single_mode = single_mode;
	}

	log(message, level = 'info') {
		const levelIndex = this.#levels[level] ?? this.#levels.info;
		const currentLevelIndex = this.#levels[this.logLevel];

		if (
			(this.single_mode && levelIndex === currentLevelIndex) ||
			(!this.single_mode && levelIndex >= currentLevelIndex)
		) {
			console.log(`${logLevelColors[level]}[${level.toUpperCase()}] ${message}\x1b[0m`);
		}
	}

	reset() {
		this.single_mode = false;
		this.logLevel = 'debug';
	}

	debug(message) {
		this.log(message, 'debug');
	}

	info(message) {
		this.log(message, 'info');
	}

	warning(message) {
		this.log(message, 'warning');
	}

	error(message) {
		this.log(message, 'error');
	}

	critical(message) {
		this.log(message, 'critical');
	}
}

export default Logger;

2024-02-17 21:59 UTC, antisedativ commented
еще у тебя твой метод не добавлен в экспорт в index.js

2024-02-17 22:07 UTC, antisedativ approved these changes

2024-02-22 09:38 UTC, merged