CLT-45
antisedativ/CharmLog pull request #41
Opened 2024-03-13 21:22 UTC by elfarr

2024-03-13 22:59 UTC, antisedativ requested changes

2024-03-13 22:59 UTC, antisedativ commented on src/index.js
> +export const charmlog = {
зачем тут экспорт?

2024-03-13 22:59 UTC, antisedativ commented on tests/index.test.js
> +import {charmlog} from '@src/index.js';
ты же можешь по дефолту импортировать charmlog
`import charmlog from '@src/index.js';`

2024-03-13 22:59 UTC, antisedativ commented on tests/index.test.js
> +console.log(typeof charmlog);
забыла лог убрать

2024-03-13 22:59 UTC, antisedativ commented on tests/index.test.js
> +            expect(charmlog[key]).toBeDefined();
не уверен что это работает корректно
попробуй "сломать" какой нибудь импорт и проверить
например, убери экспорт класса логера во второй строке и запусти тест, по идее твой тест не упадет, хотя должен

2024-03-16 20:13 UTC, antisedativ commented on tests/index.test.js
> +console.log(charm_moduls);
так зачем тут лог

2024-03-16 20:13 UTC, antisedativ commented on tests/index.test.js
> +	});
и в тесте ничего не поменялось, выше писал кейс при котором тест неправильно отрабатывает

2024-03-17 09:02 UTC, elfarr commented on tests/index.test.js
> +	});
то есть, нужно проверять, чтобы не было лишних импортов? если да, то можно ли в самом файле с тестами прописать какие модули ожидаем или это будет не очень правильно?

2024-03-17 15:05 UTC, antisedativ commented on tests/index.test.js
> +	});
по хорошему надо просто проходиться по тем методам, которые импортируются и вызывать их. Если они вызвались и отработали, то все норм

2024-03-21 16:44 UTC, antisedativ approved these changes

2024-03-21 16:44 UTC, merged